### ISSUE TITLE
Setup Guidelines for Propertynames (PascalCase instead of CamelCase)

### ISSUE THREAD

**Issue by vertonghenb** [ElderJames/ant-design-blazor#30]
Currently some of our components like a `<AntButton/>` uses camelcase for it's property names.
We should use PascalCase see `<AntBadge/>` or `<AntAlert/>`

### Todo
- [x] Add Linter #32 
- [ ] Update all Properties for all components.

**Comment by ElderJames** [comment]
I'm not sure if I'll use PascalCase because I want to be closer to the development habits of the front-end.

**Comment by vertonghenb** [comment]
C# is the front-end and the convention for Properties is PascalCase. 
More information can be found [here](https://www.c-sharpcorner.com/UploadFile/8a67c0/C-Sharp-coding-standards-and-naming-conventions/)
[Here](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/capitalization-conventions) you can find the C# conventions by Microsoft.

**Comment by ElderJames** [comment]
Ok, let's follow the convention.
I think we need to add a lint to check PRs.

**Comment by rabbitism** [comment]
I agree with this. Originally we are expecting the experience that copying existing React/Angular ant design code and make it working directly in C#, but it is painful to identify which property should be camelCase. So let's move to C# convention completely.

**Comment by vertonghenb** [comment]
#32 Helps with this issue.

**Comment by ElderJames** [comment]
fix in #82
