### ISSUE TITLE
[Input] Autosize not working correctly for TextArea

### ISSUE THREAD

**Issue by vertonghenb** [ElderJames/ant-design-blazor#34]
![a0c50ae3-23e0-4202-adfa-6892f6cd3fa1](https://user-images.githubusercontent.com/10981553/77273129-1d9d1100-6cb3-11ea-8161-15fab2e0ae5a.gif)

Maybe [this](https://www.jacklmoore.com/autosize/) script can help?

**Comment by ElderJames** [comment]
@Brian-Ding cc

**Comment by Brian-Ding** [comment]
Ant-Design they use a hidden textarea to calculate the size of the original textarea, it seems not easy to implement that in a similar way with blazor.

I will check the script you provided, thx bro! @vertonghenb

**Comment by vertonghenb** [comment]
[This post](https://stackoverflow.com/a/2032642/2585394) on StackOverflow can also help, but be cautious to read a few answers.

**Comment by vertonghenb** [comment]
So I was just playing around with some options here and this is what I came up with:

![6f971703-2f57-40c6-afb0-7c8b42d8af1f](https://user-images.githubusercontent.com/10981553/77278719-5abbd000-6cc0-11ea-8c95-6c25aa352072.gif)


- No JavaScript
- Most of it is done by CSS
- No additional parsing due to `pre-wrap`
- Using a copy element just like a lot of websites do (Facebook is one of them and the original AntDesign works the same way).
- Using the copy element to auto size the textarea.

A small demo can be found https://github.com/vertonghenb/TextareaTest

You might want to take some idea's into the change.
