### ISSUE TITLE
The extension method GetJsonAsync<T> for HttpClient is probably ambiguity

### ISSUE THREAD

**Issue by Sagilio** [ElderJames/ant-design-blazor#37]
There is a same signature method at `Microsoft.AspNetCore.Blazor.HttpClient` package.

**Comment by ElderJames** [comment]
You are right, my original intention was to make this method work on server-side and client-side

**Comment by Sagilio** [comment]
The methods at `Microsoft.AspNetCore.Blazor.HttpClient` package looks already work on server-side and client-side.

**Comment by ElderJames** [comment]
Ok, I'll delete it. Thank you.
